In [1]:
'''
    @Author: Bhupinder Singh
    @Date: 25-12-2022
    @Last Modified by: Bhupinder Singh
    @Last Modified date: 25-12-2022
    @Title: Create a 3x3 matrix with values ranging from 2 to 10.
            Expected Output:
            [[ 2 3 4]
            [ 5 6 7]
            [ 8 9 10]]
'''
import sys

from data_log import get_logger

import numpy as np

lg = get_logger(name="(program_2)", file_name="data_log.log")

In [2]:
class NumericalPython:

    def create_matrix(self):
        """
        Description:
             This function is used to Create a 3x3 matrix with values ranging from 2 to 10.
        Parameter:
            None
        Return:
            Returns None
        """
        try:
            matrix = np.arange(2,11).reshape(3, 3)
            lg.info(f" 3x3 matrix : \n{matrix}")
        except Exception:
            exception_type, _, exception_traceback = sys.exc_info()
            line_number = exception_traceback.tb_lineno
            lg.exception(
                f"Exception type : {exception_type} \nError on line number : {line_number}")

In [3]:
if __name__ == "__main__":
    np_obj = NumericalPython()
    np_obj.create_matrix()

(program_2) - 2022-12-26 10:46:15,983 - INFO -  3x3 matrix : 
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
